name: complaint_reporting_app
description: Community-based complaint reporting system with geolocation
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.6

  # HTTP & Permissions
  http: ^1.2.1
  permission_handler: ^11.3.0
  url_launcher: ^6.2.5

  # Location & Maps
  geolocator: ^11.0.0
  geocoding: ^2.1.0
  google_maps_flutter: ^2.6.0
  flutter_map: ^6.2.1
  latlong2: ^0.9.0

  # Image and File Handling
  image_picker: ^1.1.0
  path_provider: ^2.1.3
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/complaint_vector.png
    - assets/images/map.png
